server:
  port: 8087

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/admin_db?createDatabaseIfNotExist=true
    username: ${DB_USER:root}
    password: ${DB_PASS:change_me}
  jpa:
    hibernate:
      ddl-auto: update

admin:
  audit:
    enabled: true
    retention-days: 365

eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
