server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/metrics_db?createDatabaseIfNotExist=true
    username: ${DB_USER:root}
    password: ${DB_PASS:change_me}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

metrics:
  retention-days: 365

eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

