server:
  port: 8084

spring:
  datasource:
    # Primary datasource is optional; analytics reads from activity & metrics sources below
  activity:
    datasource:
      url: jdbc:mysql://localhost:3306/activities_db?createDatabaseIfNotExist=true
      username: ${ACTIVITY_DB_USER:root}
      password: ${ACTIVITY_DB_PASS:change_me}
  metrics:
    datasource:
      url: jdbc:mysql://localhost:3306/metrics_db?createDatabaseIfNotExist=true
      username: ${METRICS_DB_USER:root}
      password: ${METRICS_DB_PASS:change_me}

cache:
  redis:
    host: localhost
    port: 6379

eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

